# Generated by Django 5.2.8 on 2025-11-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_blogpost_content_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content_json',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_html',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
