# Generated by Django 5.2.8 on 2025-11-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_blogpost_content_json_blogpost_content_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_json',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_html',
            field=models.TextField(blank=True),
        ),
    ]
